name: nectar_ui
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.1.1
  path_provider: ^2.1.1

  # database
  shared_preferences: ^2.0.13
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6
  sqflite: ^2.0.3+1

  


  # ui utilities
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  badges: ^3.1.2
  carousel_slider: ^4.1.1
  dots_indicator: ^3.0.0

  # authentication and user management
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1

  # localization 
  easy_localization: ^3.0.1
  
  # routing
  auto_route: ^7.8.4

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.6
  
flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/lang/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 900